**Remember the least and make the most**

#### Representation: 
>attributes-variables = neurons in input-layer

----
>target-variables = neurons in output-layer

----
>Learning-algos = #nodes-each-layer + activation-f(a)-each-layer + search(optimization)

----
> training/fitting-model = training-set + initial-weights + learning-algos + enough-iterations

----
> trained-model = #nodes-each-layer + activation-f(a)-each-layer + best-weights-found

----
> purpose-of-training = finding the best weights

----
> predictions = test-set + trained-model

#### Evaluation

----
> model-good-bad = Error = $(y^{(i)} - \hat{y}^{(i)})^2$, i = data index, $()^2$ is better math

----
> good-model = $Error_{minimized}$

#### Optimization

----
> weights-root-2-everything = $Error_{(w_{i,j})}$ ===> $w_{i,j}$ is **tuning knob** to achieve $Error_{minimum}$

----
> weights + Error ==> derivative ==> tuning-knob == 1-unit-weight-change **Convert** (?)-unit-direction-Error-change 
- derivative guide where and how-much weights update themselves
- update weights towards $Error_{minimum}$ ==> weights = weights -=/+= learning_rate * $\frac{dError}{dw}$

----
> **Derivative is constantly changing, so weights must constantly update**
- $\Delta{w}$ => $\Delta{Error}$ => $\Delta{\frac{dE}{dw}}$=> $\Delta$magnifying-power of tuning-knob => 1-unit-weight-change **Convert** (?+$\Delta$)-unit-direction-Error-change 

----
> forward-pass: given weights + data == updated-model + data => prediction => Error

----
> backward-pass: Error => $\frac{dError}{dw}$ => new-weights = weights -=/+= learning_rate * $\frac{dError}{dw}$     

----    
> forward-pass:  new-weights + data == new-model + data => new-prediction => new-Error  

----
> backward-pass: new-Error => new-$\frac{dError}{dw}$ => $new_2$-weights = new-weights -=/+= learning_rate * new-$\frac{dError}{dw}$

----      
> iterating forward-backward-pass is the way to reach optimal
    

----

#### Normal Equation vs Gradient descent

**Normal Equation**: a fancy math calculation

Advantages: 
> no worry of learning_rate

----
> a lot of features


#### Symbols and Notations
> x, y in terms of matrix and vector

----
> more attributes: $(x_1, x_2, x_3, x_4, ...)$, target variable: $y$

----
> $x_j^{(i)}$ = the value of jth feature of the ith data example, $j\in{n}, i\in{m}$, $n$: num of features, $m$: is num of data points

----
> a row of data or a data point = a vertical vector = dimension (n,1)

----
> Multivariate linear regression model is expressed in vector-vector-multiplication
- as $\theta, x$ are **both vertical vector**
- $h_{\theta}(x) = \theta_0x_0 + \theta_1x_1 + ... = \theta^Tx$, ($x_0 = 1$)
- `np.dot(a,b)` for all vector and matrix multiplication; $a*c$ as scalar vector multiplication, $a, b \in{vector}, c \in{scalar}$ 


### np.dot can do both scalar-vector and matrix-matrix operation

In [72]:
import numpy as np

# scalar and vector multiplication
print(np.dot(3,4))
print(type(np.dot(3,4)))
print(np.dot([1,2],3))
print(np.dot(3, [1,2]))
print(type(np.dot(3, [1,2])))
print(np.dot(3, np.array([1,2])))
# dimension makes a difference
print(np.dot(np.array([1,2], ndmin=2),3))
print(type(np.dot(np.array([1,2], ndmin=2),3)))

# vector and matrix multiplication: (n,m) (m,n) must match
print(np.dot(np.array([1,2], ndmin=2),np.array([3,4], ndmin=2).T))
# be careful
print(np.dot(np.array([1,2], ndmin=2).T,np.array([3,4], ndmin=2)))
# most case usage
print(np.dot(np.array([1,2], ndmin=2),np.array([[3,4],[3,4],[3,4]], ndmin=2).T))
print(np.dot(np.array([[1,2],[1,2]], ndmin=2),np.array([[3,4],[3,4],[3,4]], ndmin=2).T))


12
<class 'numpy.int64'>
[3 6]
[3 6]
<class 'numpy.ndarray'>
[3 6]
[[3 6]]
<class 'numpy.ndarray'>
[[11]]
[[3 4]
 [6 8]]
[[11 11 11]]
[[11 11 11]
 [11 11 11]]


In [55]:
from IPython.display import Image
Image(width=300, height=200, url="https://lh3.googleusercontent.com/dKdGZ0GuPpflog5S9Iin6iZ6WvJVFW5myQdXO4oDFiYKk-KeqOw87aDpUfh15-R08sgdS6IMKoGhXRZtg4UOIjSfyaM2SwiVQ_ECzqLR3D2k4dTkMVEAs5SNQ80EL563ijSolg5gN9vYumAUoIHxTbFDzJ40RlCPXKZ3u39tJ2ogxc1AvBfT0r3G0ma_1Q3cZEoQG14Zj8KHjHHpyDFdOlbYmZai_GC4FtAlEEkmQW476NGO7H4sjM74mm00GMIcqWs-4sr9zSFo9tysRE1LtFYVmLlr4Gs0V3kJpNDhcf0mXhjDF0K_DqB-tND0poPb0oZYzKTBniusqDCRynE6KXK0oJ0LRihxOBqlb8oqQ5XIaISotLIIJMRyLIc5GGQeYpIJ4rgvcCXd_sQzxfRo4OqQxjITd5MoWzoRSOwLVCEJ8cs1FNyUcUtnhZb4_eHbFXmndHfJNU7hgpzeIG4kcycLFx-nK9Mq1TXHvrxtimiT8LOBZrH9gBNSooHNe0p6uJbz14iyC6PLmLLQoJ5z6L8b3frsdYOescZ4seYUsV814duxxl_8cjTdKlWCvXQMEKN9Lxb0aR4Qx419-RUrLfsjCuPqi6SmnBPtwaydOxUHnXy1fZY=w1416-h748-no")


In [32]:
Image(width=300, height=200, url="https://lh3.googleusercontent.com/JeJ3Q4NoZBwXLhX6fMCprF-Bbq9VA_UQhtm31sGWMqBhC5okgiRAdhpAgsmOLJLwOet50B9aDuy7dYhQNz6WvrL_AOA1Pp9Qyaq1O12oqdU183ZKEL7xqq-DEqOz_U8nfi6zc0FPGklxBktQ20_Pc8SuiRk8Z8emCcbLsiWb_L7zX41-Ax4qsJeL-Aq_EtfP-Em2EmGjZBxel-iu-xHc4K_vpbuLTt7vuK-PcLWyB-Js3NKkcYoO9kScZV8_75nbOV3OPWb6XjwbZcdEbq88w2EdCzexdMFkJgwjWoI4T_q7tA0ViTXtURB0V4D7_6xNtO9YIFhFGKj5IYQRkzVyXFr5xpfB8awRnlls6n4-9T-OVbiu07kkg533n3U0_qN_NREQNL9yTdNFKkSZxLP0P2M_qLjObe-YeKHXrPkOhP8zJPL9-yHtJ0VhH035cDAO2Q5LO-IMCtg4Rrn3YK0mTbKJwPpN_rUW8eoYqJKM4mxJa7XzVugxp6yNzOCVugNNUaaDqbqDK75I5VLMIp_4QFXR2djfEhOu5ptRBxvoC-8y81zMCOZGaVR0ispm93XA75Lv-AS_08d-F9piXajOMaiw6gkllAVVE6WY7ptejAcb7L6BUTg=w916-h840-no")

In [2]:
from IPython.display import HTML
HTML('<iframe width="500" height="300" src="https://www.youtube.com/embed/mmclAQ-UlbE?list=PLZ9qNFMHZ-A4rycgrgOYma6zxF4BZGGPW&amp;ecver=1" frameborder="0" allowfullscreen></iframe>')
# 4:11s

#### Feature scaling help reach optimal more efficiently
- try constrain within $-1 \le x \le 1$
- slightly beyond or below is fine
- or mean normalization to constraint $-0.5 \le x \le 0.5$

In [1]:
from IPython.display import HTML
HTML('<iframe width="500" height="300" src="https://www.youtube.com/embed/yQci-wS0iMw?list=PLZ9qNFMHZ-A4rycgrgOYma6zxF4BZGGPW&amp;ecver=1" frameborder="0" allowfullscreen></iframe>')
# 2:09s - 5:26s

#### Make sure gradient descent is working
- plot Error vs #iterations, Error should decrease on every iteration
- set convergence when error less than $10^{-3}$
- situation when Error keep increasing or up-down cycling, probably due to learning_rate too high (5:42s)
- try different $alpha$ from 1, 0.1, 0.01, 0.001 (8:34s)

In [3]:
from IPython.display import HTML
HTML('<iframe width="500" height="300" src="https://www.youtube.com/embed/mlHcA-VCyN0?list=PLZ9qNFMHZ-A4rycgrgOYma6zxF4BZGGPW&amp;ecver=1" frameborder="0" allowfullscreen></iframe>')

#### Choose features and non-linear functions
- select and create features and make polynomial function structure is like design neural structure for neural network model building
- create new features from existing features which would make more sense(2:11s)
- quadratic is not as meaningful as a cubic function for the problem (3:18s)
- feature scaling is applicable to new-created features (5:14s)

In [1]:
from IPython.display import HTML
HTML('<iframe width="500" height="300" src="https://www.youtube.com/embed/8p3S9aR3n4o?list=PLZ9qNFMHZ-A4rycgrgOYma6zxF4BZGGPW&amp;ecver=1" frameborder="0" allowfullscreen></iframe>')

#### Normal equation
- Not gradient descent, No iteration but get the optimal weights in one shot
- set derivative of Error = 0, to directly calculate the change of weights
- no need to worry learning_rate
- no need to worry about feature scaling
- example (4:26s) : 4 data examples, X and y, m examples, n+1 features
- Normal equation: calculate weights minimize Error in one shot $\theta = (X^TX)^{-1}X^Ty$
- pros and cons comparing gradient descent and normal equation (13:30s)
- when to use normal equation: (15:00s)
    - as long as num of features less than 1000, Ng prefer normal equation 
    - for some specific linear regression, normal equation is faster

In [2]:
from IPython.display import HTML
HTML('<iframe width="500" height="300" src="https://www.youtube.com/embed/rnlti7rgns0?list=PLZ9qNFMHZ-A4rycgrgOYma6zxF4BZGGPW&amp;ecver=1" frameborder="0" allowfullscreen></iframe>')

#### Normal equaltion and non-invertibility
- Normal equation use inversion to find best weights
- non-invertible matrix: rarely happen, when it happends software will take care of it
- causes of non-invertbility: 
    - redundant features (linearly dependent on each other): $x_1$ = size in feet, $x_2$=size in meters
    - too many features 
- solutions: delete some features for redundant or regularization for too many features

In [3]:
from IPython.display import HTML
HTML('<iframe width="500" height="300" src="https://www.youtube.com/embed/t-5Take484A?list=PLZ9qNFMHZ-A4rycgrgOYma6zxF4BZGGPW&amp;ecver=1" frameborder="0" allowfullscreen></iframe>')

#### Classification
